// <auto-generated />
using System;
using App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace App.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("App.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("Permissao")
                        .HasColumnType("integer");

                    b.Property<string>("Senha")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_apiario", b =>
                {
                    b.Property<Guid>("apa_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("apa_descricao")
                        .HasColumnType("text");

                    b.Property<string>("apa_endereco")
                        .HasColumnType("text");

                    b.Property<Guid>("api_codigoresponsavel")
                        .HasColumnType("uuid");

                    b.HasKey("apa_codigo");

                    b.HasIndex("api_codigoresponsavel");

                    b.ToTable("abe_apiario");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_apicultor", b =>
                {
                    b.Property<Guid>("api_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("api_cpfcnpj")
                        .HasColumnType("text");

                    b.Property<string>("api_nome")
                        .HasColumnType("text");

                    b.Property<bool>("api_status")
                        .HasColumnType("boolean");

                    b.Property<string>("api_telefone")
                        .HasColumnType("text");

                    b.HasKey("api_codigo");

                    b.ToTable("abe_apicultor");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_apicultorcolmeia", b =>
                {
                    b.Property<Guid>("cpi_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("api_codigo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("col_codigo")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("cpi_datainicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("cpi_principal")
                        .HasColumnType("boolean");

                    b.Property<bool>("cpi_status")
                        .HasColumnType("boolean");

                    b.HasKey("cpi_codigo");

                    b.HasIndex("api_codigo");

                    b.HasIndex("col_codigo");

                    b.ToTable("abe_apicultorcolmeia");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_colmeia", b =>
                {
                    b.Property<Guid>("col_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("col_datainstalacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("col_descricao")
                        .HasColumnType("text");

                    b.Property<decimal>("col_latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("col_longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("col_numero")
                        .HasColumnType("integer");

                    b.Property<string>("col_status")
                        .HasColumnType("text");

                    b.Property<Guid>("rac_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("col_codigo");

                    b.HasIndex("rac_codigo");

                    b.ToTable("abe_colmeia");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_inspecao", b =>
                {
                    b.Property<Guid>("ins_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("api_codigo")
                        .HasColumnType("uuid");

                    b.Property<Guid>("col_codigo")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ins_data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ins_observacao")
                        .HasColumnType("text");

                    b.Property<int>("ins_situacao")
                        .HasColumnType("integer");

                    b.HasKey("ins_codigo");

                    b.HasIndex("api_codigo");

                    b.HasIndex("col_codigo");

                    b.ToTable("abe_inspecao");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_leitura", b =>
                {
                    b.Property<Guid>("lei_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("col_codigo")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("lei_data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("lei_valor")
                        .HasColumnType("numeric");

                    b.Property<Guid>("tip_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("lei_codigo");

                    b.HasIndex("col_codigo");

                    b.HasIndex("tip_codigo");

                    b.ToTable("abe_leitura");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_log", b =>
                {
                    b.Property<Guid>("log_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("log_data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("log_operacao")
                        .HasColumnType("text");

                    b.Property<string>("log_tabela")
                        .HasColumnType("text");

                    b.Property<Guid>("usu_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("log_codigo");

                    b.HasIndex("usu_codigo");

                    b.ToTable("abe_log");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_raca", b =>
                {
                    b.Property<Guid>("rac_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("rac_descricao")
                        .HasColumnType("text");

                    b.Property<string>("rac_origem")
                        .HasColumnType("text");

                    b.Property<bool>("rac_status")
                        .HasColumnType("boolean");

                    b.HasKey("rac_codigo");

                    b.ToTable("abe_raca");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_tipodeitura", b =>
                {
                    b.Property<Guid>("tip_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("tip_descricao")
                        .HasColumnType("text");

                    b.Property<Guid>("uni_codigo")
                        .HasColumnType("uuid");

                    b.HasKey("tip_codigo");

                    b.HasIndex("uni_codigo");

                    b.ToTable("abe_tipodeitura");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_unidademedida", b =>
                {
                    b.Property<Guid>("uni_codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("uni_descricao")
                        .HasColumnType("text");

                    b.HasKey("uni_codigo");

                    b.ToTable("abe_unidademedida");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_apiario", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_apicultor", "abe_apicultor")
                        .WithMany()
                        .HasForeignKey("api_codigoresponsavel")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_apicultor");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_apicultorcolmeia", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_apicultor", "abe_apicultor")
                        .WithMany()
                        .HasForeignKey("api_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.abe_colmeia", "abe_colmeia")
                        .WithMany()
                        .HasForeignKey("col_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_apicultor");

                    b.Navigation("abe_colmeia");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_colmeia", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_raca", "abe_raca")
                        .WithMany()
                        .HasForeignKey("rac_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_raca");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_inspecao", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_apicultor", "abe_apicultor")
                        .WithMany()
                        .HasForeignKey("api_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.abe_colmeia", "abe_colmeia")
                        .WithMany()
                        .HasForeignKey("col_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_apicultor");

                    b.Navigation("abe_colmeia");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_leitura", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_colmeia", "abe_colmeia")
                        .WithMany()
                        .HasForeignKey("col_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.Domain.Entities.abe_tipodeitura", "abe_tipodeitura")
                        .WithMany()
                        .HasForeignKey("tip_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_colmeia");

                    b.Navigation("abe_tipodeitura");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_log", b =>
                {
                    b.HasOne("App.Domain.Entities.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usu_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("App.Domain.Entities.abe_tipodeitura", b =>
                {
                    b.HasOne("App.Domain.Entities.abe_unidademedida", "abe_unidademedida")
                        .WithMany()
                        .HasForeignKey("uni_codigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("abe_unidademedida");
                });
#pragma warning restore 612, 618
        }
    }
}
